# Generated by Django 3.2.4 on 2022-04-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0018_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minorder',
            field=models.TextField(default=''),
        ),
    ]
