# Generated by Django 3.2.4 on 2022-04-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cart_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='gst_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
