# Generated by Django 3.2.4 on 2022-04-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userdetail_gst_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='gst_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
