# Generated by Django 3.2.4 on 2022-04-15 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_userdetail_gst_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='gst_number',
            new_name='gst',
        ),
    ]
