# Generated by Django 3.2.4 on 2022-04-16 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_gst_number_userdetail_gst'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='gst',
            new_name='gst_Number',
        ),
    ]
