# Generated by Django 3.2.4 on 2022-04-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_gst_userdetail_gst_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='photo',
            field=models.ImageField(default='default.gif', upload_to='user_photos'),
        ),
    ]
