# Generated by Django 3.2.4 on 2022-04-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_userdetail_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='user_photos'),
        ),
    ]
